import WOWII217Connected12
import WOWII217ClosureCertificateSemantics
import WOWII217Finite13
import WOWII217ClosureSemantics
import WOWII217Finite13ClosureSharedDeg

#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.supp
#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.ConnectedComponent.neighbor_of_mem
#check Finset.card_le_card
#check Finset.card_subtype_le
#check SimpleGraph.connected_iff_exists_forall_reachable
#check SimpleGraph.Connected
#check Set.toFinset
#check Set.toFinset_card
#check Set.toFinset_card
#check Set.toFinset_diff
#check Set.toFinset_subset
#check Finset.card_diff_le
#check Finset.card_le_card
#check SimpleGraph.Walk.exists_path
#check ConnectedComponent
#check ConnectedComponent.mem_supp_iff
#check ConnectedComponent.eq
#check SimpleGraph.Adj
#check SimpleGraph.ConnectedComponent.reachable_of_mem_supp
#check SimpleGraph.ConnectedComponent.reachable_of_mem
#check SimpleGraph.ConnectedComponent.not_mem_supp
#check SimpleGraph.mem_neighborFinset
#check SimpleGraph.mem_neighborFinset
#check Finset.card_diff_card
#check Set.toFinset_mem
#check Set.toFinset_insert
#check Finset.card_union_le
#check SimpleGraph.ConnectedComponent.supp_eq
#check SimpleGraph.connected_of_forall_reachable
#check SimpleGraph.connectedComponentMk
