import Mathlib
#check SimpleGraph.connected_iff_exists_forall_reachable
#check SimpleGraph.Connected
#check SimpleGraph.ConnectedComponent
#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_congr_adj
#check SimpleGraph.ConnectedComponent.eq
#check SimpleGraph.connected_iff_exists_connected
#check SimpleGraph.connected_iff_exists_isPath
#check SimpleGraph.connected_iff_exists_reachable
#check SimpleGraph.connectivity
#check SimpleGraph.reachable
#check SimpleGraph.Reachable
#check SimpleGraph.path
#check SimpleGraph.Walk.start_mem_support
#check SimpleGraph.Walk.support
#check SimpleGraph.Walk.getVert
#check SimpleGraph.Walk.length
#check Finset.card_le_card
