import WOWII217Finite13ClosureRelSymHighLowSharedDeg
import WOWII217FiniteBase
import Mathlib
#check SimpleGraph.ConnectedComponent
#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.Walk.support
#check SimpleGraph.neighborFinset
#check SimpleGraph.ConnectedComponent.mem_supp_congr_adj
#check SimpleGraph.ConnectedComponent.supp
#check SimpleGraph.ConnectedComponent.mem_supp
#check SimpleGraph.reachableFrom
#check SimpleGraph.isConnected_iff_reachable
#check SimpleGraph.Connected
#check Finset.card_le_card
#check Finset.card_sdiff
#check Set.toFinset
#check Set.toFinset_card
#check Finset.card_diff_subtype_add_card
#check Finset.card_sdiff_add_card
#check Finset.filter_mem_iff
#check Finset.card_le_of_injective
#check SimpleGraph.ConnectedComponent.not_mem
