import Mathlib

#check SimpleGraph.Connected
#check SimpleGraph.connected_iff_exists_forall_reachable
#check SimpleGraph.connected_iff_exists_isPath
#check SimpleGraph.connected_iff
#check SimpleGraph.connected_iff_nonempty
#check SimpleGraph.Reachable
#check SimpleGraph.ConnectedComponent
#check SimpleGraph.connectedComponentMk
#check SimpleGraph.connected_iff_exists_forall_reachable
#check SimpleGraph.connected_iff_isPreconnected
#check SimpleGraph.connected_iff_exists_of_forall_reachable
#check SimpleGraph.connected_iff_forall_connected
#check SimpleGraph.connected_iff_exists_reachable
