import Mathlib
#check SimpleGraph.ConnectedComponent.supp
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.ConnectedComponent.ind
#check SimpleGraph.ConnectedComponent.supp_inj
#check SimpleGraph.ConnectedComponent.connectedToSimpleGraph
#check SimpleGraph.connected_toSimpleGraph
#check SimpleGraph.ConnectedComponent.toSimpleGraph
#check SimpleGraph.connectedComponentMk_supp_subset_supp
#check SimpleGraph.neighborFinset
#check SimpleGraph.degree
#check Finset.card_filter
#check Finset.card_subtype_iff
#check Finset.card_pos
#check Set.toFinset
#check Fintype.card_ofFinset
#check Finset.card_le_of_subset
