import WOWII217Finite13ClosureSharedDeg

open WOWII217Finite13ClosureSharedDeg
open WOWII217FiniteBase

#check completeUpper
#check fixedDegreeSequenceUpper
#check hasHighLowEdge13
#check pathClosureParallelRel13
#check connectedUpper
