import Mathlib
#check SimpleGraph.degree_le_card_neighborSet
#check SimpleGraph.card_neighborSet_le
#check SimpleGraph.card_neighborSet_eq_card_filter
#check SimpleGraph.degree_upper
#check SimpleGraph.le_card_neighborSet
#check SimpleGraph.card_neighborFinset
#check SimpleGraph.mem_neighborFinset
#check SimpleGraph.degree_upper_of_exists_path
#check SimpleGraph.degree_eq_zero_of_not_adj
#check SimpleGraph.degree_pos
#check SimpleGraph.neighborSet
#check SimpleGraph.subgraph
#check SimpleGraph.induce
#check SimpleGraph.Induce
#check SimpleGraph.neighborFinset
#check SimpleGraph.adjSubgraph_iff
#check SimpleGraph.mem_neighborFinset
