import Mathlib.Combinatorics.SimpleGraph.Connectivity.Connected
import Mathlib

open SimpleGraph
#check SimpleGraph.Finite.degree_lt_card_verts
#check SimpleGraph.Finite.card_neighborSet
#check SimpleGraph.Finite.card_neighborSet_eq_card_filter
#check SimpleGraph.degree_induce_of_neighborSet_subset
#check SimpleGraph.ConnectedComponent.toSimpleGraph
#check SimpleGraph.ConnectedComponent.connected_toSimpleGraph
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.mem_supp_of_adj_mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.connectedComponentMk
#check SimpleGraph.ConnectedComponent.support
#check SimpleGraph.ConnectedComponent.supp
#check SimpleGraph.toSimpleGraph
#check SimpleGraph.Finite.degree_lt_card
