import WOWII217ClosureSemantics
import WOWII217Connected12
import WOWII217Finite13ClosureSharedDeg
import WOWII217Finite13

#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.supp
#check SimpleGraph.ConnectedComponent.mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_iff
#check SimpleGraph.ConnectedComponent.mem_supp_of_adj_mem_supp
#check SimpleGraph.ConnectedComponent.mem_supp_of_mem_reachable
#check SimpleGraph.ConnectedComponent.mem_supp_congr_adj
#check SimpleGraph.Graph.connected
#check Finset.card_sdiff_add_card_eq_card
#check Finset.card_diff_subcard
#check Set.toFinset
#check Set.toFinset_card
#check Set.toFinset_diff
#check Fintype.card
