import WOWII217ClosureSemantics
#check BitVec.toNat
#check WOWII217FiniteBase.BoolFour
#check WOWII217FiniteBase.boolNotXor_eq_true_iff
#check WOWII217FiniteBase.boolFourValue
#check WOWII217FiniteBase.degreeBitsUpper
#check BoolFour
#check decide
#check WOWII217ClosureSemantics.boolFourValue_degreeBitsUpper_eq
#check List.length_filter
#check BitVec.ofNat
#check BitVec.toNat_ofNat
#check Nat.mod_lt
#check Nat.mod_lt_iff_lt_dvd
