import Mathlib
#check SimpleGraph.Connected
#check SimpleGraph.connected_iff
#check SimpleGraph.connected_iff_exists_reachable
#check SimpleGraph.connected_iff_forall_reachable
#check SimpleGraph.reachable
#check SimpleGraph.ConnectedComponent
#check SimpleGraph.connectedComponent
#check SimpleGraph.connected_of_forall_reachable
#check SimpleGraph.ConnectedComponent
#check SimpleGraph.conn
#check SimpleGraph.neighborSet
#check SimpleGraph.deg_le_card_neighborFinset
