import WOWII217Closure
import WOWII217FiniteBase
import WOWII217Finite13
import Mathlib

#check SimpleGraph.Reachable
#check SimpleGraph.Adj.reachable
#check SimpleGraph.Reachable.trans
#check graphOfUpper
#check fixedDegreeSequenceUpper
#check WOWII217FiniteBase.degreeUpperNat
#check WOWII217FiniteBase.degreeBitsUpper
#check WOWII217Finite13.zeroDegreeBlocksPattern13
#check WOWII217Closure.adjUpper
#check List.all_eq_true
#check Finset.card_filter
#check Finset.card_filter_lt
#check Set.Finite
#check Finite
#check SetLike
