import Mathlib
open SimpleGraph
#check connected_iff_exists_forall_reachable
#check Connected
#check not_connected_iff
#check Reachable
#check SimpleGraph.Conn
#check connectedComponent
#check SimpleGraph.connectedComponentMk
#check SimpleGraph.ConnectedComponent.support
#check SimpleGraph.ConnectedComponent.card
#check SimpleGraph.ConnectedComponent.fintype
#check SimpleGraph.ConnectedComponent.nonempty_iff
#check SimpleGraph.ConnectedComponent.mem_support_iff
#check SimpleGraph.ConnectedComponent.outDegree
#check SimpleGraph.connectedComponent
#check SimpleGraph.connectedComponent_eq
#check SimpleGraph.connectedComponentMk
